Repository Shopify/cli, pull requests merged in 2022-09, with the labels that each got.

#437 Move the UI extensions' build logic from Go to Node
  .eslintignore
  packages/app/package.json
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/models/app/extensions.ts
  packages/app/src/cli/models/app/loader.ts
  packages/app/src/cli/services/build.ts
  packages/app/src/cli/services/build/extension.ts
  packages/app/src/cli/services/deploy/bundle.ts
  packages/app/src/cli/services/dev.ts
  packages/app/src/cli/services/dev/extension.ts
  packages/app/src/cli/services/environment.test.ts
  packages/app/src/cli/services/environment/id-manual-matching.test.ts
  packages/app/src/cli/services/environment/id-matching.test.ts
  packages/app/src/cli/services/environment/identifiers.test.ts
  packages/app/src/cli/services/extensions/bundle.test.ts
  packages/app/src/cli/services/extensions/bundle.ts
  packages/app/src/cli/services/web.ts
  packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts
  packages/app/src/cli/utilities/app/http-reverse-proxy.ts
  packages/app/src/cli/utilities/extensions/configuration.test.ts
  packages/app/src/cli/utilities/extensions/configuration.ts
  packages/cli-kit/src/error.ts
  packages/features/steps/create-app.steps.ts
  yarn.lock
Labels: cla-needed

#465 Add customer-accounts surface to ui-extensions-server-kit
  packages/ui-extensions-server-kit/src/ExtensionServerClient/types.ts
Labels: gsd:23677

#376 Rename scaffold-to-generate
  .vscode/launch.json
  README.md
  dev.yml
  docs/eslint-rules.md
  docs/get-started.md
  fixtures/app/package.json
  packages/app/src/cli/commands/app/generate/extension.test.ts
  packages/app/src/cli/commands/app/generate/extension.ts
  packages/app/src/cli/commands/app/scaffold/extension.ts
  packages/app/src/cli/prompts/generate/extension.test.ts
  packages/app/src/cli/prompts/generate/extension.ts
  packages/app/src/cli/services/environment/identifiers.ts
  packages/app/src/cli/services/generate/extension.integration.test.ts
  packages/app/src/cli/services/generate/extension.test.ts
  packages/app/src/cli/services/generate/extension.ts
  packages/features/steps/app.steps.ts
  packages/features/steps/create-app.steps.ts
  packages/ui-extensions-go-cli/api/api.go
Labels: cla-needed

#454 Add `extension_directories` attribute to `shopify.app.toml`
  .changeset/cyan-tables-retire.md
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/models/app/app.ts
  packages/app/src/cli/models/app/loader.test.ts
  packages/app/src/cli/models/app/loader.ts
  packages/app/src/cli/services/dev/select-app.test.ts
  packages/app/src/cli/services/environment.test.ts
  packages/app/src/cli/services/environment/identifiers.test.ts
  packages/app/src/cli/services/info.test.ts
  packages/app/src/cli/services/web-env.test.ts
Labels: cla-needed

#467 Expose extension points and categories in ExtensionPayload
  packages/app/src/cli/utilities/extensions/configuration.ts
  packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.test.tsx
  packages/ui-extensions-server-kit/src/testing/extensions.ts
  packages/ui-extensions-server-kit/src/types.ts
Labels: gsd:23677

#389 `tunnel` flag and default localhost
  .changeset/new-fireants-sin.md
  packages/app/src/cli/commands/app/dev.ts
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/models/app/app.ts
  packages/app/src/cli/prompts/dev.test.ts
  packages/app/src/cli/prompts/dev.ts
  packages/app/src/cli/services/dev.ts
  packages/app/src/cli/services/dev/output.ts
  packages/app/src/cli/services/dev/urls.test.ts
  packages/app/src/cli/services/dev/urls.ts
  packages/app/src/cli/services/environment.ts
  packages/cli-kit/src/store.ts
  packages/ui-extensions-go-cli/api/api_test.go
  packages/ui-extensions-go-cli/api/root/templates/checkout_post_purchase/tunnel-error.html.tpl
  packages/ui-extensions-go-cli/api/root/templates/tunnel-error.html.tpl
Labels: includes-post-release-steps

#466 [Feature] Pass new permissions to apps during `yarn dev` to enable new functionality for Checkout UI Extensions
  .changeset/spicy-parrots-reflect.md
  packages/app/src/cli/models/organization.ts
  packages/app/src/cli/prompts/dev.test.ts
  packages/app/src/cli/services/dev.ts
  packages/app/src/cli/services/dev/extension.ts
  packages/app/src/cli/services/dev/fetch.test.ts
  packages/app/src/cli/services/dev/select-app.test.ts
  packages/app/src/cli/services/env/pull.test.ts
  packages/app/src/cli/services/env/show.test.ts
  packages/app/src/cli/services/environment.test.ts
  packages/app/src/cli/services/environment.ts
  packages/app/src/cli/services/info.test.ts
  packages/app/src/cli/utilities/extensions/configuration.test.ts
  packages/app/src/cli/utilities/extensions/configuration.ts
  packages/cli-kit/src/api/graphql/create_app.ts
  packages/cli-kit/src/api/graphql/find_app.ts
  packages/cli-kit/src/api/graphql/find_org.ts
  packages/ui-extensions-go-cli/core/core.go
  packages/ui-extensions-go-cli/core/core_test.go
Labels: #gsd:30317

#523 Tunnel by default again
  .changeset/nervous-deers-play.md
  packages/app/src/cli/commands/app/dev.ts
  packages/app/src/cli/services/dev/urls.test.ts
  packages/app/src/cli/services/dev/urls.ts
Labels: includes-post-release-steps
