Repository Shopify/cli, pull requests merged in 2023-07, with the labels that each got.

#2282 Add none template
  .changeset/many-chefs-invent.md
  packages/create-app/oclif.manifest.json
  packages/create-app/src/prompts/init.test.ts
  packages/create-app/src/prompts/init.ts
Labels: #gsd:31406

#2368 remove the update action from theme update_extension schema
  packages/theme/src/cli/services/update/check.test.ts
  packages/theme/src/cli/services/update/schemas/update_extension_schema_v1.ts
Labels: #gsd:33653

#2534 Fix Thank You page redirect URLs
  packages/app/src/cli/services/dev/extension/utilities.test.ts
  packages/app/src/cli/services/dev/extension/utilities.ts
Labels: gsd:32079
