Repository Shopify/cli, pull requests merged in 2024-04, with the labels that each got.

#3645 [Themes] Fix Theme Push Execution when password flag is provided
  .changeset/dull-tips-wait.md
  packages/theme/src/cli/commands/theme/push.test.ts
  packages/theme/src/cli/commands/theme/push.ts
  packages/theme/src/cli/services/push.ts
Labels: Area: @shopify/theme

#3651 [3.58] Fix `shopify theme push` issue when password flag is provided
  .changeset/dull-tips-wait.md
  packages/theme/src/cli/commands/theme/push.test.ts
  packages/theme/src/cli/commands/theme/push.ts
  packages/theme/src/cli/services/push.ts
Labels: Area: Housekeeping

#3669 [Themes] Improve Glob Pattern subdirectory mismatch error handling
  .changeset/spotty-badgers-attack.md
  packages/theme/src/cli/utilities/asset-ignore.test.ts
  packages/theme/src/cli/utilities/asset-ignore.ts
Labels: Type: Bug, Area: @shopify/theme

#3673 Add changeset for Theme Push theme selection text update
  .changeset/silver-mails-build.md
Labels: Area: @shopify/theme

#3605 Migrate payment extensions in dev deploy if eligible
  packages/app/src/cli/api/graphql/extension_migrate_app_module.ts
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/services/context/identifiers-extensions.ts
  packages/app/src/cli/services/dev/migrate-app-module.test.ts
  packages/app/src/cli/services/dev/migrate-app-module.ts
  packages/app/src/cli/utilities/developer-platform-client.ts
  packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
  packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
Labels: #gsd:37340

#3690 Add esbuild back, improve esbuild plugin import, fix app info
  package.json
  packages/app/src/cli/services/extensions/bundle.test.ts
  packages/app/src/cli/services/extensions/bundle.ts
  packages/app/src/cli/services/info.test.ts
  packages/app/src/cli/services/info.ts
  packages/features/steps/app.steps.ts
  pnpm-lock.yaml
Labels: #gsd:36803

#3691 Add is-global with global utilities
  packages/cli-kit/src/public/node/is-global.test.ts
  packages/cli-kit/src/public/node/is-global.ts
Labels: #gsd:36803

#3633 [Theme] Add handling when server does not respond to bulk asset upload
  packages/cli-kit/src/public/node/themes/api.test.ts
  packages/cli-kit/src/public/node/themes/api.ts
  packages/cli-kit/src/public/node/themes/factories.ts
  packages/theme/src/cli/utilities/theme-uploader.ts
Labels: Area: @shopify/theme

#3727 Refactor webhook trigger command to handle organization switches
  .changeset/tricky-carrots-press.md
  docs-shopify.dev/commands/interfaces/app-webhook-trigger.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/app/src/cli/commands/app/webhook/trigger.ts
  packages/app/src/cli/prompts/webhook/trigger.test.ts
  packages/app/src/cli/prompts/webhook/trigger.ts
  packages/app/src/cli/services/context.ts
  packages/app/src/cli/services/webhook/find-app-info.test.ts
  packages/app/src/cli/services/webhook/find-app-info.ts
  packages/app/src/cli/services/webhook/trigger-flags.test.ts
  packages/app/src/cli/services/webhook/trigger-flags.ts
  packages/app/src/cli/services/webhook/trigger-options.test.ts
  packages/app/src/cli/services/webhook/trigger-options.ts
  packages/app/src/cli/services/webhook/trigger.test.ts
  packages/app/src/cli/services/webhook/trigger.ts
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  pnpm-lock.yaml
Labels: includes-post-release-steps

#3821 [Themes] Improve clarity of tests for push command
  packages/theme/src/cli/commands/theme/push.test.ts
Labels: Area: @shopify/theme
