Repository Shopify/cli, pull requests merged in 2024-06, with the labels that each got.

#4029 Connect JSON schema contracts to CLI
  packages/app/src/cli/api/graphql/extension_specifications.ts
  packages/app/src/cli/services/generate/fetch-extension-specifications.ts
  packages/app/src/cli/utilities/json-schema.ts
  packages/cli-kit/package.json
  packages/cli-kit/src/public/node/json-schema.test.ts
  packages/cli-kit/src/public/node/json-schema.ts
  pnpm-lock.yaml
Labels: #gsd:37045

#4046 [Log Streaming] Removing references to event_type in log streaming.
  packages/app/src/cli/prompts/function/replay.test.ts
  packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
  packages/app/src/cli/services/app-logs/poll-app-logs.ts
  packages/app/src/cli/services/app-logs/write-app-logs.test.ts
  packages/app/src/cli/services/app-logs/write-app-logs.ts
  packages/app/src/cli/services/function/replay.test.ts
  packages/app/src/cli/services/function/replay.ts
Labels: #gsd:39776

#4043 Allow declarative webhooks template
  .vscode/settings.json
  packages/app/src/cli/models/app/app.ts
Labels: #gsd:36745

#3933 Pass Development Server flags down to theme environment
  packages/theme/src/cli/commands/theme/dev.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/services/dev.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
  packages/theme/src/cli/utilities/theme-environment/types.ts
Labels: Area: @shopify/theme, #gsd:40767

#4112 supported buyer context: disallow mixed definition types
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/base_payments_app_extension_schema.test.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/base_payments_app_extension_schema.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.test.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.test.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/offsite_payments_app_extension_schema.test.ts
  packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.test.ts
Labels: #gsd:38440
