Repository Shopify/cli, pull requests merged in 2024-05, with the labels that each got.

#3822 [Themes] Remove and replace UnpublishedThemeManager
  packages/theme/src/cli/commands/theme/push.test.ts
  packages/theme/src/cli/commands/theme/push.ts
  packages/theme/src/cli/utilities/unpublished-theme-manager.test.ts
  packages/theme/src/cli/utilities/unpublished-theme-manager.ts
Labels: Area: @shopify/theme

#3830 [Themes] `Theme Dev` Dev Preview Flag
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/dev.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/services/dev.ts
Labels: Area: @shopify/theme

#3877 [Refactor][Themes] Move local disk 'delete' and 'write' operations behind the ThemeFileSystem interface
  packages/cli-kit/src/public/node/themes/types.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/utilities/asset-ignore.test.ts
  packages/theme/src/cli/utilities/theme-downloader.test.ts
  packages/theme/src/cli/utilities/theme-downloader.ts
  packages/theme/src/cli/utilities/theme-fs.test.ts
  packages/theme/src/cli/utilities/theme-fs.ts
  packages/theme/src/cli/utilities/theme-fs/theme-fs-mock-factory.ts
Labels: Area: @shopify/theme

#3891 Introduce new remote renderer for `shopify theme dev`
  packages/cli-kit/src/public/node/http.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/services/dev.ts
  packages/theme/src/cli/utilities/theme-environment/cookies.test.ts
  packages/theme/src/cli/utilities/theme-environment/cookies.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-utils.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-utils.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
  packages/theme/src/cli/utilities/theme-environment/types.ts
Labels: #gsd:40767

#3916 Tidy up app loading, pt2
  packages/app/src/cli/commands/app/config/use.ts
  packages/app/src/cli/commands/app/deploy.ts
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/models/app/app.ts
  packages/app/src/cli/models/app/loader.test.ts
  packages/app/src/cli/models/app/loader.ts
  packages/app/src/cli/models/extensions/extension-instance.ts
  packages/app/src/cli/models/extensions/specification.ts
  packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_app_home.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_app_proxy.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_branding.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_point_of_sale.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_webhook.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_webhook.ts
  packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
  packages/app/src/cli/prompts/config.ts
  packages/app/src/cli/prompts/dev.test.ts
  packages/app/src/cli/prompts/dev.ts
  packages/app/src/cli/services/app/config/link-service.test.ts
  packages/app/src/cli/services/app/config/link.test.ts
  packages/app/src/cli/services/app/config/link.ts
  packages/app/src/cli/services/app/config/use.ts
  packages/app/src/cli/services/app/select-app.ts
  packages/app/src/cli/services/app/write-app-configuration-file.ts
  packages/app/src/cli/services/context.ts
  packages/app/src/cli/services/context/breakdown-extensions.ts
  packages/app/src/cli/services/dev.ts
  packages/app/src/cli/services/dev/prompt-helpers.ts
  packages/app/src/cli/services/dev/select-app.test.ts
  packages/app/src/cli/services/dev/select-app.ts
  packages/app/src/cli/services/generate-schema.ts
  packages/app/src/cli/services/generate/extension.test.ts
  packages/app/src/cli/services/generate/fetch-extension-specifications.ts
  packages/app/src/cli/services/local-storage.ts
  packages/app/src/cli/services/webhook/trigger.ts
  packages/app/src/cli/utilities/app/config/getTomls.ts
  packages/app/src/cli/utilities/developer-platform-client.ts
  packages/cli-kit/src/public/node/fs.ts
  packages/eslint-plugin-cli/rules/required-fields-when-loading-app.js
  packages/theme/src/cli/services/pull.test.ts
Labels: #gsd:37045

#3937 [Themes] Theme Dev - Update description for noDelete flag
  docs-shopify.dev/commands/interfaces/theme-dev.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/dev.ts
Labels: Area: Documentation

#3918 Add log polling to `dev` command
  packages/app/src/cli/api/graphql/subscribe_to_app_logs.ts
  packages/app/src/cli/constants.ts
  packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
  packages/app/src/cli/services/app-logs/poll-app-logs.ts
  packages/app/src/cli/services/app-logs/write-app-logs.test.ts
  packages/app/src/cli/services/app-logs/write-app-logs.ts
  packages/app/src/cli/services/dev/processes/app-logs-polling.ts
  packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
  packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
  packages/app/src/cli/utilities/developer-platform-client.ts
  packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
  packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
  packages/cli-kit/src/private/node/constants.ts
  packages/cli-kit/src/public/node/logs.ts
Labels: #gsd:39776

#3930 Hydrogen bundling
  .changeset/ten-clocks-attend.md
  bin/bundling/clean-bundled-dependencies.js
  docs-shopify.dev/commands/examples/hydrogen-customer-account-push.example.sh
  docs-shopify.dev/commands/hydrogen-customer-account-push.doc.ts
  docs-shopify.dev/commands/interfaces/hydrogen-build.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-codegen.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-customer-account-push.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-debug-cpu.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-deploy.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-dev.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-env-pull.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-generate-route.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-generate-routes.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-init.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-preview.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-setup-css.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-setup.interface.ts
  docs-shopify.dev/commands/interfaces/hydrogen-upgrade.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  package.json
  packages/cli-kit/src/public/node/custom-oclif-loader.ts
  packages/cli/README.md
  packages/cli/bin/bundle.js
  packages/cli/oclif.manifest.json
  packages/cli/package.json
  packages/cli/src/cli/commands/hydrogen/init.ts
  packages/cli/src/hooks/init.ts
  packages/cli/src/index.ts
  packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts
  pnpm-lock.yaml
  shipit.experimental.yml
Labels: includes-post-release-steps
