Repository Shopify/cli, pull requests merged in 2024-11, with the labels that each got.

#4660 Port fetchThemeAssets / fetchChecksums to graphQL
  packages/cli-kit/src/cli/api/graphql/admin/generated/get_theme_file_bodies.ts
  packages/cli-kit/src/cli/api/graphql/admin/generated/get_theme_file_checksums.ts
  packages/cli-kit/src/cli/api/graphql/admin/generated/types.d.ts
  packages/cli-kit/src/cli/api/graphql/admin/queries/get_theme_file_bodies.graphql
  packages/cli-kit/src/cli/api/graphql/admin/queries/get_theme_file_checksums.graphql
  packages/cli-kit/src/public/node/api/admin.ts
  packages/cli-kit/src/public/node/themes/api.test.ts
  packages/cli-kit/src/public/node/themes/api.ts
  packages/theme/src/cli/constants.ts
  packages/theme/src/cli/utilities/batching.ts
  packages/theme/src/cli/utilities/theme-downloader.test.ts
  packages/theme/src/cli/utilities/theme-downloader.ts
  packages/theme/src/cli/utilities/theme-environment/theme-polling.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-polling.ts
  packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.ts
  packages/theme/src/cli/utilities/theme-fs.test.ts
Labels: #gsd:40351

#4771 Import flow_trigger_discovery_webhook and migrate to flow trigger callback
  packages/app/src/cli/commands/app/import-extensions.ts
  packages/app/src/cli/services/flow/extension-to-toml.ts
Labels: gsd:43206

#4723 Ruby Removal - Remove code references
  .eslintrc.cjs
  .ruby-version
  bin/create-test-app.js
  dev.yml
  docs/cli/architecture.md
  docs/cli/cross-os-compatibility.md
  packages/cli-kit/package.json
  packages/cli-kit/project.json
  packages/cli-kit/src/public/node/analytics.test.ts
  packages/cli-kit/src/public/node/analytics.ts
  packages/cli-kit/src/public/node/error-handler.ts
  packages/cli-kit/src/public/node/ruby.test.ts
  packages/cli-kit/src/public/node/ruby.ts
  packages/theme/src/cli/services/pull.test.ts
Labels: #gsd:40767

#4791 [Themes] Improve storefront password protection redirect handling
  packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
Labels: #gsd:40767

#4813 [Themes] Fix empty files in host themes during `app dev`
  .changeset/great-zoos-punch.md
  packages/cli-kit/src/public/node/themes/api.test.ts
  packages/cli-kit/src/public/node/themes/api.ts
Labels: #gsd:40767

#4810 [Themes] Verify existence of required theme files before initializing storefront session
  .changeset/brown-dots-clap.md
  packages/theme/src/cli/utilities/theme-environment/dev-server-session.test.ts
  packages/theme/src/cli/utilities/theme-environment/dev-server-session.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
Labels: #gsd:40767

#4900 Add --strict flag to theme push to enforce theme check before pushing
  .changeset/chilly-donkeys-exist.md
  docs-shopify.dev/commands/interfaces/theme-push.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/check.ts
  packages/theme/src/cli/commands/theme/push.ts
  packages/theme/src/cli/services/push.test.ts
  packages/theme/src/cli/services/push.ts
Labels: Area: @shopify/theme
