Repository Shopify/cli, pull requests merged in 2024-08, with the labels that each got.

#4245 Add 'required_scopes' to 'access_scope' toml schema
  .changeset/fluffy-lobsters-melt.md
  packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts
  packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts
Labels: #gsd:39564

#4238 Fix URL validation in the app schema
  .changeset/selfish-turkeys-vanish.md
  packages/app/src/cli/models/app/loader.test.ts
  packages/app/src/cli/models/app/validation/common.ts
  packages/app/src/cli/models/extensions/specifications/validation/common.ts
Labels: #gsd:38439

#4183 [Themes] - Shopify Theme Console
  .changeset/cuddly-yaks-laugh.md
  docs-shopify.dev/commands/interfaces/theme-console.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/cli-kit/src/public/node/http.ts
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/console.ts
  packages/theme/src/cli/services/console.test.ts
  packages/theme/src/cli/services/console.ts
  packages/theme/src/cli/services/local-storage.ts
  packages/theme/src/cli/utilities/repl/evaluator.test.ts
  packages/theme/src/cli/utilities/repl/evaluator.ts
  packages/theme/src/cli/utilities/repl/presenter.test.ts
  packages/theme/src/cli/utilities/repl/presenter.ts
  packages/theme/src/cli/utilities/repl/repl-theme-manager.test.ts
  packages/theme/src/cli/utilities/repl/repl-theme-manager.ts
  packages/theme/src/cli/utilities/repl/repl.test.ts
  packages/theme/src/cli/utilities/repl/repl.ts
  packages/theme/src/cli/utilities/repl/storefront-password-prompt.test.ts
  packages/theme/src/cli/utilities/repl/storefront-password-prompt.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
Labels: #gsd:40767

#4295 [Themes] Console - Make storefront password storage sticky
  packages/theme/src/cli/services/local-storage.ts
  packages/theme/src/cli/utilities/repl/storefront-password-prompt.test.ts
  packages/theme/src/cli/utilities/repl/storefront-password-prompt.ts
Labels: #gsd:40767

#4156 [Themes][app dev][TAE] Find or Create host theme when preparing theme app extension preview
  packages/app/src/cli/services/dev/processes/theme-app-extension-next.test.ts
  packages/app/src/cli/services/dev/processes/theme-app-extension-next.ts
  packages/app/src/cli/utilities/host-theme-manager.test.ts
  packages/app/src/cli/utilities/host-theme-manager.ts
  packages/app/src/cli/utilities/host-theme-watcher.test.ts
  packages/app/src/cli/utilities/host-theme-watcher.ts
  packages/cli-kit/src/public/node/themes/api.ts
  packages/cli-kit/src/public/node/themes/theme-manager.ts
  packages/cli-kit/src/public/node/themes/types.ts
Labels: Area: @shopify/theme, #gsd:40767

#4325 Update the new `shopify theme dev` command so that it does not delete generated assets
  packages/cli-kit/src/public/node/themes/api.test.ts
  packages/cli-kit/src/public/node/themes/api.ts
  packages/theme/src/cli/services/push.test.ts
  packages/theme/src/cli/services/push.ts
  packages/theme/src/cli/utilities/theme-uploader.test.ts
  packages/theme/src/cli/utilities/theme-uploader.ts
Labels: #gsd:40767

#4327 [Refactor] Move HostThemeManager and HostThemeManager into themes app extensions utilities directory
  packages/app/src/cli/services/dev/processes/theme-app-extension-next.test.ts
  packages/app/src/cli/services/dev/processes/theme-app-extension-next.ts
  packages/app/src/cli/services/dev/processes/theme-app-extension.ts
  packages/app/src/cli/utilities/extensions/theme/host-theme-manager.test.ts
  packages/app/src/cli/utilities/extensions/theme/host-theme-manager.ts
  packages/app/src/cli/utilities/extensions/theme/host-theme-watcher.test.ts
  packages/app/src/cli/utilities/extensions/theme/host-theme-watcher.ts
Labels: #gsd:40767

#4351 Introduce support to password protected stores
  docs-shopify.dev/commands/interfaces/theme-dev.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/dev.ts
  packages/theme/src/cli/services/console.test.ts
  packages/theme/src/cli/services/console.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/services/dev.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.ts
Labels: #gsd:40767

#4302 [Theme] New dev command
  docs-shopify.dev/commands/interfaces/theme-dev.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/cli-kit/src/public/node/http.ts
  packages/cli-kit/src/public/node/themes/factories.ts
  packages/cli-kit/src/public/node/themes/types.ts
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/theme/package.json
  packages/theme/project.json
  packages/theme/src/cli/commands/theme/dev.ts
  packages/theme/src/cli/services/console.test.ts
  packages/theme/src/cli/services/console.ts
  packages/theme/src/cli/services/dev.test.ts
  packages/theme/src/cli/services/dev.ts
  packages/theme/src/cli/utilities/asset-checksum.test.ts
  packages/theme/src/cli/utilities/asset-checksum.ts
  packages/theme/src/cli/utilities/repl/evaluator.ts
  packages/theme/src/cli/utilities/theme-environment/hot-reload/client.ts
  packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
  packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
  packages/theme/src/cli/utilities/theme-environment/html.ts
  packages/theme/src/cli/utilities/theme-environment/local-assets.ts
  packages/theme/src/cli/utilities/theme-environment/proxy.test.ts
  packages/theme/src/cli/utilities/theme-environment/proxy.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
  packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
  packages/theme/src/cli/utilities/theme-environment/theme-polling.test.ts
  packages/theme/src/cli/utilities/theme-environment/types.ts
  packages/theme/src/cli/utilities/theme-fs.test.ts
  packages/theme/src/cli/utilities/theme-fs.ts
  packages/theme/src/cli/utilities/theme-fs/theme-fs-mock-factory.ts
  packages/theme/src/cli/utilities/theme-uploader.test.ts
  packages/theme/src/cli/utilities/theme-uploader.ts
  pnpm-lock.yaml
Labels: #gsd:40767

#4281 Add allow_direct_linking to UIExtension schema
  packages/app/src/cli/models/extensions/schemas.ts
  packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
  packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Labels: #gsd:39317

#4386 [Theme Dev] - Skip JSON reconciliation when development theme is empty
  packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.test.ts
  packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.ts
Labels: #gsd:40767

#4367 [Themes][Feature] Dev Server - Handle theme editor sync conflicts between local and remote themes
  packages/theme/src/cli/constants.ts
  packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.test.ts
  packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
  packages/theme/src/cli/utilities/theme-environment/theme-polling.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-polling.ts
  packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.test.ts
  packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.ts
  packages/theme/src/cli/utilities/theme-fs.test.ts
  packages/theme/src/cli/utilities/theme-fs.ts
Labels: #gsd:40767

#4382 Use the `--dev-preview` beta flag in the `shopify theme pull` command
  packages/cli/oclif.manifest.json
  packages/theme/src/cli/commands/theme/console.ts
  packages/theme/src/cli/commands/theme/pull.test.ts
  packages/theme/src/cli/commands/theme/pull.ts
  packages/theme/src/cli/services/dev.ts
  packages/theme/src/cli/services/pull.ts
Labels: #gsd:40767
