Repository Shopify/cli, pull requests merged in 2025-01, with the labels that each got.

#5203 [Themes] Add debug logging for theme fetch errors
  packages/cli-kit/src/public/node/themes/api.ts
Labels: Area: @shopify/theme

#5004 Remove all conditional logic around App Management being disabled
  .github/workflows/shopify-cli.yml
  packages/app/src/cli/services/deploy/bundle.test.ts
  packages/app/src/cli/services/deploy/bundle.ts
  packages/app/src/cli/services/dev/fetch.test.ts
  packages/app/src/cli/utilities/developer-platform-client.ts
  packages/cli-kit/src/private/node/api/headers.ts
  packages/cli-kit/src/private/node/constants.ts
  packages/cli-kit/src/private/node/session.ts
  packages/cli-kit/src/private/node/session/exchange.test.ts
  packages/cli-kit/src/private/node/session/exchange.ts
  packages/cli-kit/src/private/node/session/scopes.test.ts
  packages/cli-kit/src/private/node/session/scopes.ts
  packages/cli-kit/src/public/node/context/local.test.ts
  packages/cli-kit/src/public/node/context/local.ts
Labels: dont-merge

#5274 RemoteSpecfication includes uidIsClientProvided
  packages/app/src/cli/api/graphql/app-management/generated/specifications.ts
  packages/app/src/cli/api/graphql/app-management/queries/specifications.graphql
  packages/app/src/cli/api/graphql/extension_specifications.ts
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
  packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
  packages/eslint-plugin-cli/rules/no-inline-graphql.js
Labels: #gsd:37045

#5276 Drive DCDD from server specifications
  packages/app/src/cli/models/app/app.test-data.ts
  packages/app/src/cli/models/app/app.ts
  packages/app/src/cli/models/app/loader.ts
  packages/app/src/cli/models/extensions/load-specifications.ts
  packages/app/src/cli/models/extensions/specification.ts
  packages/app/src/cli/models/extensions/specifications/custom_data.ts
  packages/app/src/cli/services/generate/fetch-extension-specifications.test.ts
  packages/app/src/cli/services/generate/fetch-extension-specifications.ts
Labels: #gsd:37045
