Repository Shopify/cli, pull requests merged in 2025-09, with the labels that each got.

#6387 Add error message and file to ExtensionPayload interface
  .changeset/khaki-crews-help.md
  packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
  packages/app/src/cli/services/dev/extension.ts
  packages/app/src/cli/services/dev/extension/payload/models.ts
  packages/ui-extensions-server-kit/src/types.ts
Labels: #gsd:47105

#5923 Add LoadingBar UI component
  packages/cli-kit/src/private/node/ui/components/LoadingBar.test.tsx
  packages/cli-kit/src/private/node/ui/components/LoadingBar.tsx
  packages/cli-kit/src/private/node/ui/components/Tasks.test.tsx
  packages/cli-kit/src/private/node/ui/components/Tasks.tsx
Labels: no-pr-activity

#5924 Add useExitOnCtrlC hook
  packages/cli-kit/src/private/node/ui/components/Tasks.tsx
  packages/cli-kit/src/private/node/ui/hooks/use-exit-on-ctrl-c.test.ts
  packages/cli-kit/src/private/node/ui/hooks/use-exit-on-ctrl-c.ts
Labels: no-pr-activity

#5925 Introduce SingleTask component
  packages/cli-kit/bin/documentation/examples.ts
  packages/cli-kit/src/private/node/ui/components/SingleTask.test.tsx
  packages/cli-kit/src/private/node/ui/components/SingleTask.tsx
  packages/cli-kit/src/public/node/ui.test.ts
  packages/cli-kit/src/public/node/ui.tsx
Labels: no-pr-activity

#6163 Release the React Router template
  .changeset/polite-coats-pay.md
  docs-shopify.dev/commands/interfaces/app-init.interface.ts
  docs-shopify.dev/generated/generated_docs_data.json
  packages/app/src/cli/prompts/init/init.test.ts
  packages/app/src/cli/prompts/init/init.ts
  packages/cli/README.md
  packages/cli/oclif.manifest.json
  packages/create-app/oclif.manifest.json
Labels: gsd:45278, #gsd:45278
