Repository Shopify/cli, pull requests merged in 2025-04, with the labels that each got.

#5472 Improve loading bar resizes
  packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx
Labels: stale-exempt

#5604 Add CLI token support for app management and BP API
  .changeset/tasty-terms-brake.md
  packages/app/src/cli/api/graphql/business-platform-destinations/generated/user-info.ts
  packages/app/src/cli/api/graphql/business-platform-destinations/queries/user-info.graphql
  packages/app/src/cli/utilities/developer-platform-client.ts
  packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
  packages/cli-kit/src/private/node/session/exchange.test.ts
  packages/cli-kit/src/private/node/session/exchange.ts
  packages/cli-kit/src/private/node/session/scopes.test.ts
  packages/cli-kit/src/private/node/session/scopes.ts
  packages/cli-kit/src/public/node/context/local.test.ts
  packages/cli-kit/src/public/node/context/local.ts
  packages/cli-kit/src/public/node/session.test.ts
  packages/cli-kit/src/public/node/session.ts
Labels: #gsd:43158

#5699 Bump theme check & language libs
  .changeset/stale-melons-invent.md
  packages/app/package.json
  packages/theme/package.json
  pnpm-lock.yaml
Labels: #gsd:44310

#5709 Merge main fixes
  .changeset/quick-planes-try.md
  packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
  packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
  packages/app/src/cli/models/extensions/specifications/ui_extension.ts
  packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
  packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Labels: includes-post-release-steps

#5727 [Fix][Themes] Remove asset upload errors for files that are renamed / deleted
  .changeset/sweet-colts-film.md
  packages/theme/src/cli/utilities/theme-fs.test.ts
  packages/theme/src/cli/utilities/theme-fs.ts
Labels: Area: @shopify/theme
